//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyetcoweb2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reunion
    {
        public int Id { get; set; }
        public string Titulo { get; set; }
        public Nullable<System.DateTime> Dia_hora { get; set; }
        public Nullable<int> IDUsuario { get; set; }
        public string Virtual { get; set; }
        public string Cliente { get; set; }
    }
}
