//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyetcoweb2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ticket
    {
        public int Id { get; set; }
        public string Titulo { get; set; }
        public string detalle { get; set; }
        public string quien_reporto { get; set; }
        public string Cliente_id { get; set; }
        public string Estado_Actual { get; set; }
    }
}
